export const GET_ALL_FONTS_SUCCESS = 'GET_ALL_FONTS_SUCCESS';
export const GET_ALL_CATEGORIES_SUCCESS = 'GET_ALL_CATEGORIES_SUCCESS';

export const CHANGE_FONTFAMILY_SUCCESS = 'CHANGE_FONTFAMILY_SUCCESS';
export const CHANGE_FONTSIZE_SUCCESS = 'CHANGE_FONTSIZE_SUCCESS';
export const CHANGE_CATEGORY_SUCCESS = 'CHANGE_CATEGORY_SUCCESS';
export const CHANGE_FONTCOLOR_SUCCESS = 'CHANGE_FONTCOLOR_SUCCESS';
export const CHANGE_BACKGROUNDCOLOR_SUCCESS = 'CHANGE_BACKGROUNDCOLOR_SUCCESS';
